# https://github.com/japaric/trust
dist: trusty
language: rust
rust:
  - stable
services: docker

matrix:
  include:
    - env: TARGET=x86_64-unknown-linux-gnu
    - env: TARGET=x86_64-pc-windows-gnu
    - env: TARGET=x86_64-apple-darwin
      os: osx

before_install:
  - set -e
  - rustup self update

install:
  - cargo install cross

script:
  - sh scripts/cross_build.sh

deploy:
  api_key: $API_KEY
  file_glob: true
  file: zpm-$TRAVIS_TAG-$TARGET.*
  on:
    tags: true
  provider: releases
  skip_cleanup: true

branches:
  only:
    - /^v?\d+\.\d+\.\d+.*$/
    - cross-build
    - master