# https://github.com/japaric/trust
dist: trusty
language: rust
rust:
  - stable
services: docker
os: linux

jobs:
  include:
    - env: TARGET=arm-unknown-linux-gnueabi
    - env: TARGET=aarch64-unknown-linux-gnu
    - env: TARGET=x86_64-unknown-linux-gnu
    - env: TARGET=x86_64-pc-windows-gnu
    - env: TARGET=x86_64-apple-darwin
      os: osx

install:
  - cargo install cross

script:
  - sh scripts/cross_build.sh

deploy:
  provider: releases
  api_key: $TOKEN
  file_glob: true
  file: zpm-$TRAVIS_TAG-$TARGET.*
  on:
    tags: true
  skip_cleanup: true

branches:
  only:
    - /^v?\d+\.\d+\.\d+.*$/