version: 2.1
jobs:
  build:
    docker:
      - image: circleci/rust
    steps:
      - checkout
      - run: rustc --version; cargo --version; rustup --version
      - restore_cache:
          keys:
            - v1-cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}
      - run:
          name: Build
          command: RUSTFLAGS="-D warnings" cargo build --release
      - save_cache:
          paths:
            - /usr/local/cargo/registry
            - target/debug/.fingerprint
            - target/debug/build
            - target/debug/deps
          key: v1-cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}
  test:
    docker:
      - image: circleci/rust
    steps:
      - checkout
      - run: rustc --version; cargo --version; rustup --version
      - restore_cache:
          keys:
            - v1-cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}
      - run:
          name: Check format
          command: cargo fmt --all -- --check
      - run:
          name: Run tests
          command: RUSTFLAGS="-D warnings" cargo test --release
  integration_test:
    docker:
      - image: circleci/rust
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}
      - run: |
          curl -LSfs get.zokrat.es | sh
          cargo install --path .
          sh test.sh
workflows:
  version: 2
  main:
    jobs:
      - build
      - test
      - integration_test
        filters:
          branches:
            only:
              - develop
              - master
        requires:
          - build
          - test